server:
    port: 8080

spring:
    main:
        allow-bean-definition-overriding: true
    profiles:
        active: local
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:aq-project}
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:}
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    sql:
        init:
            mode: never

jwt:
    secret: ${JWT_SECRET:default-secret-key-for-development-only-change-in-production}
    access-token-validity-in-seconds: 3600 # 1시간
    refresh-token-validity-in-seconds: 604800 # 7일

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
        url: /v3/api-docs
        display-request-duration: true
        groups-order: ASC
